[project]
name = "The-Luau-Stack"
version = "1.0.0"
description = ""
authors = [{ name = "boatbomber", email = "zack@boatbomber.com" }]
readme = "README.md"
requires-python = "3.11.*"
dependencies = [
    "ipywidgets (>=8.1.5,<9.0.0)",
    "ipykernel (>=6.29.5,<7.0.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "datasets (>=3.4.1,<4.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
